/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户注册
         * @description 创建用户并返回 accessToken/refreshToken
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户登录
         * @description 使用邮箱或用户名 + 密码登录，返回 accessToken/refreshToken
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户信息 */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 注册请求 */
        RegisterRequest: {
            /**
             * @description 邮箱
             * @example test@example.com
             */
            email: string;
            /**
             * @description 密码
             * @example Password123
             */
            password: string;
            /**
             * @description 确认密码
             * @example Password123
             */
            confirmPassword: string;
            /**
             * @description 用户名
             * @example guoguo
             */
            username: string;
            /**
             * @description 是否同意用户协议
             * @example true
             */
            agreeToTerms?: boolean;
        };
        /** @description 统一响应包装 */
        ApiResponseAuthResponse: {
            /** @description 是否成功 */
            success?: boolean;
            /** @description 业务码 */
            code?: string;
            /** @description 提示信息 */
            message?: string;
            data?: components["schemas"]["AuthResponse"];
        };
        /** @description 认证响应 */
        AuthResponse: {
            user?: components["schemas"]["UserDTO"];
            /** @description 访问令牌 */
            accessToken?: string;
            /** @description 刷新令牌 */
            refreshToken?: string;
            /**
             * @description 令牌类型
             * @example Bearer
             */
            tokenType?: string;
            /**
             * Format: int64
             * @description access token 过期时间(秒)
             */
            expiresIn?: number;
        };
        /** @description 用户信息 */
        UserDTO: {
            /**
             * Format: int64
             * @description 用户ID
             */
            id?: number;
            /** @description 用户名 */
            username?: string;
            /** @description 邮箱 */
            email?: string;
            /** @description 显示名称 */
            displayName?: string;
            /** @description 头像URL */
            avatarUrl?: string;
            /** @description 个人简介 */
            bio?: string;
            /** @description 角色列表 */
            roles?: string[];
            /**
             * Format: date-time
             * @description 创建时间
             */
            createdAt?: string;
        };
        /** @description 登录请求 */
        LoginRequest: {
            /**
             * @description 邮箱/用户名
             * @example test@example.com
             */
            email: string;
            /**
             * @description 密码
             * @example Password123
             */
            password: string;
        };
        /** @description 统一响应包装 */
        ApiResponseUserDTO: {
            /** @description 是否成功 */
            success?: boolean;
            /** @description 业务码 */
            code?: string;
            /** @description 提示信息 */
            message?: string;
            data?: components["schemas"]["UserDTO"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseAuthResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseAuthResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseUserDTO"];
                };
            };
        };
    };
}
